# -*- Makefile -*-
#
# Makefile.WinCE - Makefile rules for WindowsCE
#

PDA_WIDTH = 640

PREF = /usr/arm-mingw32ce

INCS = `$(PREF)/bin/sdl-config --cflags` `$(PREF)/bin/freetype-config --cflags`

LIBS = -static `$(PREF)/bin/sdl-config --libs` -lSDL_ttf -lSDL_image -lSDL_mixer -lSDL -lfreetype -ljpeg -lpng -lz -lbz2 -lmad

# QVGA (320x240)
#DEFS = -DWINCE -DWIN32 -DPDA_WIDTH=320 -DBPP16 -DUTF8_CAPTION -DUTF8_FILESYSTEM

# VGA (640x480)
DEFS = -DWINCE -DWIN32 -DPDA_WIDTH=${PDA_WIDTH} -DBPP16 -DUTF8_CAPTION -DUTF8_FILESYSTEM

# recommended: OggVorbis 
#DEFS += -DUSE_OGG_VORBIS
#LIBS += -logg -lvorbis -lvorbisfile

# optional: Integer OggVorbis
DEFS += -DUSE_OGG_VORBIS -DINTEGER_OGG_VORBIS
LIBS += -lvorbisidec -logg

EXESUFFIX = .exe
OBJSUFFIX = .o

.SUFFIXES:
.SUFFIXES: $(OBJSUFFIX) .cpp .h

CC = arm-mingw32ce-g++ 
LD = arm-mingw32ce-g++ -o

CFLAGS = -O3 -Wall -fno-rtti -fno-check-new -fomit-frame-pointer -pipe -c $(INCS) $(DEFS)
RM = rm -f

TARGET = onscripter$(EXESUFFIX)
EXT_OBJS = 

include Makefile.onscripter
